[package]
name = "shanimation-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = "0.3.1"
error-stack-derive = "0.1.0"
image = "0.24.6"
imageproc = "0.23.0"
